apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component-whhr
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component-whhr
    app.kubernetes.io/part-of: test-app-qcpo
  name: test-component-whhr
  namespace: build-e2e-hacbs-qrnp
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: test-component-whhr
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: test-component-whhr
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/test-images:c9d0356bce8d4d69a17e144847d0ebe6
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8081
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8081
        resources: {}
status: {}
